### ISSUE TITLE
Cannot install smacc_viewer in ubuntu 20.04

### ISSUE THREAD

**Issue by Deeparaj-24** [reelrbtx/SMACC#118]
- I followed the instructions in [Link](https://smacc.dev/smacc-viewer/) , but I am not able to get it running. 
![Screenshot from 2023-09-01 08-21-13](https://github.com/robosoft-ai/SMACC/assets/48970406/bd14df23-e2e1-4418-b4bf-a102c5ca0cb6)
I am just getting the above error.

┆Issue is synchronized with this [Jira Task](https://robosoft-ai.atlassian.net/browse/SMACC1-49) by [Unito](https://www.unito.io)

**Comment by brettpac** [comment]
Hi @Deeparaj-24,
We retired the SMACC Viewer a couple of months ago. It just got too expensive to maintain. But we created a version of the new SMACC Run-Time Analyzer for or ROS1 users, and still free for individual and academic use. Here are the installation instructions... https://robosoft.ai/smacc1_rta-installation/

Please lemme know if you run into any issues. Thank you.

**Comment by Deeparaj-24** [comment]
I installed the individual smacc_rta version but it is asking for the licence key. I tried the key inside the 
`~/.local/share/robosoft.ai/SMACC2 Runtime Analyzer` folder. It was not working.
![Screenshot from 2023-09-02 07-51-14](https://github.com/robosoft-ai/SMACC/assets/48970406/cf99178e-45d1-45a9-89f2-730d449cf488)

**Comment by brettpac** [comment]
Yup, so add the appropriate product to the cart and checkout... https://robosoft.ai/product-category/smacc1-runtime-analyzer/
and you'll get the license key you need.

**Comment by Deeparaj-24** [comment]
Got it. Thank you so much
