### ISSUE TITLE
Unable to sudo apt-get install 

### ISSUE THREAD

**Issue by ariccspstk** [reelrbtx/SMACC#120]
Hi i am new to ros and i was wondering why i cant find the package when i sudo apt-get install ros-melodic-smacc-viewer 

```E: Unable to locate package ros-melodic-smacc-viewer
```

┆Issue is synchronized with this [Jira Task](https://robosoft-ai.atlassian.net/browse/SMACC1-51) by [Unito](https://www.unito.io)

**Comment by brettpac** [comment]
Hi @ariccspstk 
This is an older issue but I wanted to resolve it.

The SMACC Viewer has been retired and replaced with the SMACC1 RTA (for ROS1).
Which can be found here...
https://robosoft.ai/product-category/smacc1-runtime-analyzer/
And here are the installation instructions...
https://robosoft.ai/smacc1_rta-installation/
