### ISSUE TITLE
unable to install ros-melodic-smacc-rta

### ISSUE THREAD

**Issue by ariccspstk** [reelrbtx/SMACC#121]
sudo apt-get  install ros-melodic-smacc-rta
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-melodic-smacc-rta : Depends: ros-melodic-smacc but it is not installable
E: Unable to correct problems, you have held broken packages.

┆Issue is synchronized with this [Jira Task](https://robosoft-ai.atlassian.net/browse/SMACC1-52) by [Unito](https://www.unito.io)

**Comment by brettpac** [comment]
Hi @ariccspstk,
This is an older issue but I wanted to resolve it.

The SMACC Viewer has been retired and replaced with the SMACC1 RTA (for ROS1).
Which can be found here... 
https://robosoft.ai/product-category/smacc1-runtime-analyzer/ 
And here are the installation instructions...
https://robosoft.ai/smacc1_rta-installation/
