### ISSUE TITLE
SMACC Viewer For Ubuntu20.04

### ISSUE THREAD

**Issue by astroxyx** [reelrbtx/SMACC#24]
hello ,now I can run smacc in 20.04 by delete some client and modify the boost.But I alse want to use SMACC Viewer in 20.04.Can you release version 20.04?

**Comment by reelrobotics** [comment]
Hi Astroxyx,
We expect to have a version for 20.04 by the end of this week.

**Comment by astroxyx** [comment]
Thank you very much.

**Comment by astroxyx** [comment]
> Hi Astroxyx,
> We expect to have a version for 20.04 by the end of this week.

Thank you very much.

**Comment by pabloinigoblasco** [comment]
We already have an initial version of the smacc_viewer in the noetic-devel branch of the smacc viewer.
Please, have a look to it.
Any feedback about errors or bugs is welcome.
Kind regards.

**Comment by astroxyx** [comment]
Hi Pabloinigoblasco,
But the smacc viewer is closed source,I can not install it in 20.04.

**Comment by astroxyx** [comment]
Excuse me,can you tell me how can I install install smacc viewer in 20.04? It is closed source.

**Comment by pabloinigoblasco** [comment]
Hello.

Have a look to these instructions: https://smacc.dev/smacc-viewer/
Please, replace the ROS version (from kinetic or melodic) to noetic.

Any feedback you may have is welcome.

**Comment by Deeparaj-24** [comment]
I cannot get it to work in noetic

**Comment by Belal111125** [comment]
apt-get ros-noetic-smacc-viewer is not working in noetic

**Comment by Belal111125** [comment]
@Deeparaj-24  try to use the runtime analyzer=>  https://robosoft.ai/smacc1_rta-installation/
