### ISSUE TITLE
migrate to github actions for CI

### ISSUE THREAD

**Issue by tylerjw** [reelrbtx/SMACC#32]
Would you like me to make a PR to migrate the CI from travis to github actions?  We have migrated the moveit repos to github actions as travis has gotten slower and slower and github actions is much more nicely integrated into github.

**Comment by tylerjw** [comment]
Maybe hold off on this, it looks like travis is working just fine here.

**Comment by reelrobotics** [comment]
I agree. I think we'll eventually do this, but with everything working fine at the moment, I think it's probably best to leave it alone. Thank you for the offer though.
