### ISSUE TITLE
University project

### ISSUE THREAD

**Issue by NatkaB** [reelrbtx/SMACC#44]
I am a student and I am writing my diploma project about BTs and also about SMACC. I do not know a lot about SMACC even though I tried examining your documentation and tutorials. Is there any possibility that You could help me and explain to me how to create a simple state machine using SMACC. I am supposed to create two state machines: one- very simple just to show the transitions between states (example of opening a fridge and getting a drink from it), two - more complicated state machine working on a simulation of a robot (for example pick and place). I would be very thankful for any help from You.

**Comment by brettpac** [comment]
Here is how I make new state machines....

Copy the SM (folder) you're going to use as your base (sm_atomic, sm_threesome, are good choices)
Rename your new SM folder (sm_atomic to sm_my_project)

Go into your config folder...
Change the yaml file name from sm_atomic.yaml to sm_my_project.yaml

Go into your include folder...
Change the name of the folder to sm_my_project.yaml
Change the name of the state machine header file to sm_my_project.hpp

Go into the launch folder...
Change the name of the .launch file to sm_my_project.yaml
Rename the name of the .py file to sm_my_project.py

Go into the src folder...
Change the state machine filename from sm_atomic_node.cpp to sm_my_project_node

Search and Replace
sm_atomic with sm_my_project

Search and Replace
SmAtomic with SmMyProject

And that's it. Compile and Run.

Source workspace, type...
ros run sm_my_project sm_my_project_node

And you should be good.
