### ISSUE TITLE
[BUG] Linux output redirection causes segfault.

### ISSUE THREAD

**Issue by ZhenshengLee** [reelrbtx/SMACC#48]
This odd_manager_node is a SMACC-based ros node that handles system error of robotics.

```sh
/home/nvidia/catkin_ws_drivers/devel/lib/odd_manager/odd_manager_node > /dev/null 2>&1
Segmentation fault
```

Any Idea of avoiding this?

Thanks.

**Comment by pabloinigoblasco** [comment]
Hello.
I miss some information in your case.  Today we introduced some fixes, that may be related with your issue.
We try to reproduce your issue with a basic state machine and we do not get that error:

`
$ ./devel/lib/sm_atomic/sm_atomic_node > /dev/null 2>&1
`
Please, make us know if that issue persists.
Kind regards.

**Comment by ZhenshengLee** [comment]
> Please, make us know if that issue persists.

This issue has been fixed.

Thanks for all!
