### ISSUE TITLE
Fast state transition caused segfault

### ISSUE THREAD

**Issue by rbtchun3** [reelrbtx/SMACC#59]
Hey,

I got the error while spamming smacc with button press ros messages to trigger fast state transitions,
```__pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed 

I wonder if any has seen this and possible way to debug this.

**Comment by pabloinigoblasco** [comment]
Hello.
We need more information to reproduce that.
Could you please describe in more detail what did you do to get those messages?
