### ISSUE TITLE
ModuleNotFoundError: No module named 'wx' (noetic)

### ISSUE THREAD

**Issue by antoan** [reelrbtx/SMACC#89]
After installing dependencies and running some state machines, I run the viewer and get the error below?

```
rosrun smacc_viewer smacc_viewer_node.py

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/smacc_viewer/smacc_viewer_node.py", line 6, in <module>
    from wx.html import HtmlWindow
ModuleNotFoundError: No module named 'wx'

```

┆Issue is synchronized with this [Jira Task](https://robosoft-ai.atlassian.net/browse/SMACC1-28) by [Unito](https://www.unito.io)

**Comment by brettpac** [comment]
Hi Antoan,
After going back and forth internally on this one, we finally decided that its time to retire the SMACC Viewer. 
But we've got a solution for you.

We backported the SMACC Run-Time Analyzer to ROS1, and you can find it [here](https://robosoft.ai/product-category/smacc1-runtime-analyzer/), with installation instructions [here](https://robosoft.ai/smacc1_rta-installation/).
Its free for academic and personal use.

Please let us know if you have any problems.
